# Generated by Django 5.2.14 on 2026-06-26 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=64, unique=True)),
                ('complaint', models.TextField()),
                ('language', models.CharField(blank=True, default='en', max_length=8)),
                ('channel', models.CharField(blank=True, default='', max_length=32)),
                ('user_type', models.CharField(blank=True, default='unknown', max_length=16)),
                ('campaign_context', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant_transaction_id', models.CharField(blank=True, max_length=64, null=True)),
                ('evidence_verdict', models.CharField(max_length=24)),
                ('case_type', models.CharField(max_length=48)),
                ('severity', models.CharField(max_length=16)),
                ('department', models.CharField(max_length=32)),
                ('agent_summary', models.TextField()),
                ('recommended_next_action', models.TextField()),
                ('customer_reply', models.TextField()),
                ('human_review_required', models.BooleanField(default=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('injection_detected', models.BooleanField(default=False)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('counterparty', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(max_length=16)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to='core.ticket')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
